apiVersion: v1
data:
  database-name: c29uYXI=
  database-password: c29uYXI=
  database-user: c29uYXI=
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: null
  labels:
    app: sonarqube_db
    template: postgresql-persistent-template
  name: postgresql
  selfLink: /api/v1/namespaces/andrew-sonarqube/secrets/postgresql
type: Opaque
